version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
  deploy:
    machine:
      enabled: true
    steps:
#      - add_ssh_keys:
#          fingerprints:
#            - $SSH_FINGERPRINT
      - run:
          name: Deploy
          command: |
            sudo apt-get install ncftp -y
            ncftpput -zR -u $FTP_USERNAME -p$FTP_PASSWORD $FTP_URL $FTP_DIRECTORY build/*

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master 
